config/routes.rb
Rails.application.routes.draw do
  # devise_for :users

  devise_for :users, controllers: {
  registrations: "registrations",
}

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :stockitems do
    resource :bids, only: [:new, :create, :index]
    # resource :orders, only: [:new, :create, :show]
  end
  resources :orders, except: [:destroy]
  resources :bids, only: :destroy
  resources :catalogitems, except: [:destroy]
  resources :orderstatuses, only: [:index]
  resources :users, only: [:show, :index]
  resources :transactions, only: [:show] do
    resources :payments, only: [:new, :create]
  end
end

app/models/stockitem.rb
class Stockitem < ApplicationRecord
  belongs_to :user, foreign_key: "usersell_id"
  belongs_to :catalogitem
  has_many :bids, dependent: :destroy
  has_one :order
end

app/controllers/stockitems_controller.rb
class StockitemsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  def show
    @stockitem = Stockitem.find(params[:id])
    @bids = Bid.where(stockitem_id: @stockitem.id).sort { |a,b| a.bid_price <=> b.bid_price }.reverse
    @orders = Order.where(stockitem_id: @stockitem.id)
    shoesize
  end

  def index
    @stockitems = Stockitem.where(sold_status: false)
    @stockitems_highestbids = []
    @stockitems.each do |s|
      @highest_bid = Bid.where(stockitem_id: s.id).sort { |a,b| a.bid_price <=> b.bid_price }.reverse.first
      if @highest_bid
        @highest_bid_price = @highest_bid.bid_price
      else
        @highest_bid_price = 0
      end
      @stockitems_highestbids << @highest_bid_price
    end
    shoesize
  end

  def new
    @stockitem = Stockitem.new
    @catalogitem = Catalogitem.find(params[:format])
    shoesize
  end

  def create
    @stockitem = Stockitem.new(stockitem_params)
    @stockitem.catalogitem_id = params[:catalogitem_id]
    @stockitem.user = current_user
    @stockitem.internal_size = params[:internal_size]
    if @stockitem.internal_size == 0
      flash[:alert] = "Please select a shoesize"
      redirect_to new_stockitem_path(@stockitem.catalogitem_id)
    else
      @stockitem.save!
      redirect_to stockitems_path
    end
  end

  def edit
    @stockitem = Stockitem.find(params[:id])
  end

  def update
    # @stockitem = Stockitem.find(params[:id])
    # @stockitem.sold_status = true
    # @stockitem.update!(stockitem_params2)
    # redirect_to stockitems_path
  end

  def destroy
    @stockitem = Stockitem.find(params[:id])
    @stockitem.destroy
    redirect_to stockitems_path
  end

  private

  def stockitem_params
    params.require(:stockitem).permit(:sell_price, :usersell_id, :dead_stock, :internal_size, :catalogitem_id)
  end

  def stockitem_params2
    params.permit(:sell_price, :usersell_id, :dead_stock, :internal_size, :catalogitem_id)
  end

end

app/views/stockitems/edit.html.erb
<h1>Congratulations!!!!</h1>
<p>
  You are now the proud owner of <%= @stockitem.catalogitem.description %>
</p>


 <button class="knop-1"><%= link_to "To stockitems", stockitems_path %></button>

app/views/stockitems/edit.old.html.erb
<h1>Congratulations!!!!</h1>
<p>
  You are now the proud owner of <%= @stockitem.catalogitem.description %>
</p>


<%= form_for @stockitem, url: {action: "update"} do |s| %>
  <div>
    <input type="hidden", name = "sold_status", value = true >
  </div>
  <div class="form-actions">
    <%= s.submit "Go back to stock-items", class: 'knop-1' %>
  </div>
<% end %>

app/views/stockitems/index.html.erb
<!-- <div class="development">
  developer info: <br />
  <%# if current_user %>
    current_user: <%#= current_user.email  %>
  <%# else %>
    no user logged in
  <%# end %>
</div> -->
<div class="justify">
  <h1>Market</h1>
  <%= button_to "I am Selling!", catalogitems_path, method: "get", class: "knop-1" %>
</div>
<div class="container-fluid">
  <div class="row">
    <% highest_bids_index = 0 %>
    <% @stockitems.each do |s| %>
      <div class="col-xs-12 col-sm-6 tst-stockitem">
        <div class="catalog-title parent-header">
          <div class="catalog-description-head">
            <%= s.catalogitem.description %>, Size: <%= @shoesizes[s.internal_size] %> (<%= @region %>)
          </div>
          <% if user_signed_in? %>
            <% if s.usersell_id == @current_user.id %>
              <button class="btn-small">
                <%= link_to 'Remove',  stockitem_path(s),  method: :delete, data: { confirm: 'Are you sure?' } %>
              </button>
            <% end %>
          <% end %>
        </div>
        <div>
        <%= image_tag s.catalogitem.photo, class: "img-responsive"%>
        </div>
        <div class="catalog-title parent">
          <div class="catalog-description">
            Sell: € <%= s.sell_price %> Highest Bid: € <%= @stockitems_highestbids[highest_bids_index] %>
            <% highest_bids_index += 1 %>
          </div>
          <%= button_to "New Bid", stockitem_path(s), method: "get", class: "btn-small" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/stockitems/new.html.erb
<div class="development">
  developer info: <br />
  current_user: <%= current_user.email  %>
</div>

<%= form_for @stockitem, url: {action: "create"} do |b| %>
    <label>Sales Price: <br />
      <%= b.number_field :sell_price , min: 1, max: 100000, required: true, autofocus: false, placeholder: 'Euro' %>
    </label>
    <%#= b.collection_select :catalogitem_id, Catalogitem.all, :id, :description, include_blank: false %>
    <label><%= @catalogitem.brand %> <%= @catalogitem.description %>, <%= @catalogitem.colour %>
      <input type="hidden", name = "catalogitem_id", value="<%= @catalogitem.id  %>">
    </label>
    <label>Shoesize (<%= @region %>) :
      <select id="selectShoesize">
        <% @shoesizes.each_with_index do |s, i| %>
          <option value="<%= i %>"><%= s %></option>
        <% end %>
      </select>
      <div id="internal_size">
        <input onkeydown="return false", placeholder="select size" required>
      </div>
    </label>
    <div class="form-actions">
        <%= b.submit "Sell!", class: 'knop-1' %>
    </div>
<% end %>

app/views/stockitems/show.html.erb
 <div class="development">
  developer info: <br />
  <% if current_user %>
    current_user: <%= current_user.email  %>
  <% else %>
    no user logged in
  <% end %>
</div>
<div class="image">
  <%= image_tag @stockitem.catalogitem.photo, class: "img-responsive"%>
</div>
<div class="container-fluid">
      <div class="text-box1">
        Try to buy <%= @stockitem.catalogitem.description %>, size <%= @shoesizes[@stockitem.internal_size] %> (<%= @region %>)
      </div>
  <div class="row stockitem-data">
    <div class="col-xs-4 col-sm-3">
      <ul>
        <li>Selling price:</li>
        <li>Brand:</li>
        <li>Description:</li>
        <li>Release Date:</li>
        <li>Product Code:</li>
        <li>Colour:</li>
        <li>Size:</li>
      </ul>
    </div>
    <div class="col-xs-8 col-sm-6">
        <ul>
          <li>€ <%= @stockitem.sell_price %></li>
          <li><%= @stockitem.catalogitem.brand %></li>
          <li><%= @stockitem.catalogitem.description %></li>
          <li><%= @stockitem.catalogitem.release_date %></li>
          <li><%= @stockitem.catalogitem.product_code %></li>
          <li><%= @stockitem.catalogitem.colour %></li>
          <li><%= @shoesizes[@stockitem.internal_size] %> (<%= @region %>)</li>
        </ul>
    </div>
    <div class="col-sm-3 hidden-xs">
      <div class="text-box1">
        Bid History:
      </div>
      <div>
        <% @bids.each do |b| %>
          <div>
            € <%= b.bid_price %>
            <% if user_signed_in? %>
              <% if b.userbuy_id == @current_user.id %>
                <button class="btn-small">
                  <%= link_to 'delete',  bid_path(b),  method: :delete, data: { confirm: 'Are you sure?' } %>
                </button>
              <% end %>
            <% end %>
          </div>
        <% end %>
      </div>
      <%= button_to "New Bid", new_stockitem_bids_path(@stockitem), method: "get", class: "knop-1" %>
    </div>
  </div>
</div>
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12 hidden-sm hidden-md hidden-lg">
      <div class="text-box1">
        Highest bid:
      </div>
      <div>
        <% @bids.each do |b| %>
          <div>
            € <%= b.bid_price %>
            <% if user_signed_in? %>
              <% if b.userbuy_id == @current_user.id %>
                <button class="btn-small">
                  <%= link_to 'delete',  bid_path(b),  method: :delete, data: { confirm: 'Are you sure?' } %>
                </button>
              <% end %>
            <% end %>
          </div>
        <% end %>
      </div>
      <%= button_to "New Bid", new_stockitem_bids_path(@stockitem), method: "get", class: "knop-1" %>
    </div>
  </div>
</div>