config/routes.rb
Rails.application.routes.draw do
  # devise_for :users

  devise_for :users, controllers: {
  registrations: "registrations",
}

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :stockitems do
    resource :bids, only: [:new, :create, :index]
    # resource :orders, only: [:new, :create, :show]
  end
  resources :orders, except: [:destroy]
  resources :bids, only: :destroy
  resources :catalogitems, except: [:destroy]
  resources :orderstatuses, only: [:index]
  resources :users, only: [:show, :index]
  resources :transactions, only: [:show] do
    resources :payments, only: [:new, :create]
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "startrade.jpg", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Home", root_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Market", stockitems_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Catalogue", catalogitems_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "user.jpg", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to user_path(current_user) do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars fa-2x dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li>
          <%= link_to "Market", stockitems_path, class: "navbar-wagon-item navbar-wagon-link" %>
        </li>
        <li>
          <%= link_to "Catalogue", catalogitems_path, class: "navbar-wagon-item navbar-wagon-link" %>
        </li>
        <li>
          <%= link_to "Home", root_path, class: "navbar-wagon-item navbar-wagon-link" %>
        </li>
        <% if user_signed_in? %>
          <li>
            <%= link_to user_path(current_user) do %>
              <i class="fa fa-user"></i> <%= "Profile" %>
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <i class="fa fa-sign-out"></i>  <%= "Log out" %>
            <% end %>
          </li>
        <% else %>
          <%= link_to "Login", new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
        <% end %>
      </ul>
    </div>
  </div>
</div>