config/routes.rb
Rails.application.routes.draw do
  # devise_for :users

  devise_for :users, controllers: {
  registrations: "registrations",
}

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :stockitems do
    resource :bids, only: [:new, :create, :index]
    # resource :orders, only: [:new, :create, :show]
  end
  resources :orders, except: [:destroy]
  resources :bids, only: :destroy
  resources :catalogitems, except: [:destroy]
  resources :orderstatuses, only: [:index]
  resources :users, only: [:show, :index]
  resources :transactions, only: [:show] do
    resources :payments, only: [:new, :create]
  end
end

app/models/catalogitem.rb
class Catalogitem < ApplicationRecord
  has_many :stockitems
end

app/controllers/catalogitems_controller.rb
class CatalogitemsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  def index
    @catalogitems = Catalogitem.all
  end

  def show
    @catalogitem = Catalogitem.find(params[:id])
  end

  def new
    @catalogitem = Catalogitem.new
  end

  def create
    @catalogitem = Catalogitem.new(catalogitem_params)
    @catalogitem.save!
    redirect_to catalogitems_path
  end

  def edit
    @catalogitem = Catalogitem.find(params[:id])
  end

  def update
    @catalogitem = Catalogitem.find(params[:id])
    @catalogitem.update!(catalogitem_params)
    redirect_to catalogitems_path
  end

  private

  def catalogitem_params
    params.require(:catalogitem).permit(:release_date, :colour, :retail_price, :photo, :brand, :description, :product_code, :category)
  end
end

app/views/catalogitems/edit.html.erb
<h2>Change details <%= @catalogitem.description %> </h2>

<%= simple_form_for(@catalogitem, as: @catalogitem, url: catalogitem_path(@catalogitem.id), html: { method: :put }) do |c| %>
  <%= c.error_notification %>

  <div class="form-inputs">
    <%= c.input :description, required: false, autofocus: true %>
    <%= c.input :release_date, required: false%>
    <%= c.input :colour, required: false %>
    <%= c.input :photo, required: false %>
    <%= c.input :brand, required: false %>
    <%= c.input :product_code, required: false %>
    <%= c.input :category, required: false %>
    <%= c.input :retail_price, required: false %>
  </div>
  <div class="form-actions">
    <%= c.button :submit, "Update" %>
  </div>
<% end %>
<%= link_to "Back", :back %>

app/views/catalogitems/index.html.erb
<!--  <div class="development">
  developer info: <br />
  <%# if current_user %>
    current_user: <%#= current_user.email  %>
  <%# else %>
    no user logged in
  <%# end %>
</div> -->
<h1>Catalogue</h1>
<div class="container-fluid">
  <div class="row">
    <% @catalogitems.each do |c| %>
      <div class="col-xs-12 col-sm-6 tst">
        <%= image_tag c.photo, class: "img-responsive"%>
        <div class="catalog-title parent">
          <div class="catalog-description">
            <%= c.description %>
          </div>
          <%= button_to "Details", catalogitem_path(c), method: "get", class: "btn-small" %>
          <%= button_to "Sell", new_stockitem_path(c), method: "get", class: "btn-small" %>
          <% if user_signed_in? && current_user.admin %>
            <%= button_to "Edit", edit_catalogitem_path(c), method: "get", class: "btn-small" %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>
<div class="justify">
  <% if  user_signed_in? && current_user.admin %>
    <%= button_to "New", new_catalogitem_path, method: "get", class: "knop-1" %>
  <% end %>
  <%= button_to "home", root_path, method: "get", class: "knop-1" %>
</div>

app/views/catalogitems/new.html.erb
<% if current_user.admin %>
  <h1>New Catalogue Item</h1>
  <%= form_for @catalogitem, url: {action: "create"} do |c| %>
    <%= c.label 'Retail Price:' %>
    <%= c.number_field :retail_price, min: 1, max: 100000, required: true, autofocus: false, placeholder: 'Euro' %>
    Release Date:
    <%= c.label "Release Date:"%>
    <%= c.date_field :release_date, required: true, autofocus: false, placeholder: 'date' %>
    <%= c.label "Colour:"  %>
    <%= c.text_field :colour, required: true, autofocus: false, placeholder: 'colour' %>
    <%= c.label "Brand:" %>
    <%= c.text_field :brand, required: true, autofocus: false, placeholder: 'Brand name' %>
    <%= c.label "description:" %>
    <%= c.text_field :description, required: true, autofocus: false, placeholder: 'what is it exactly?' %>
    <%= c.label "Brand specific product code (be exact please)"  %>
    <%= c.text_field :product_code, required: true, autofocus: false, placeholder: 'Product code' %>
    <%= c.label "Photo:"  %>
    <%= c.text_field :photo, required: true, autofocus: false, placeholder: 'filename' %>
    <div class="form-actions">
      <%= c.submit "Register", class: 'knop-1' %>
    </div>
  <% end %>
<% else %>
  <% flash[:alert] = "You're not auhtorised" %>
  <%= button_to "Home", root_path, method: "get" %>
<% end %>

app/views/catalogitems/show.html.erb
 <div class="development">
  developer info: <br />
  <% if current_user %>
    current_user: <%= current_user.email  %>
  <% else %>
    no user logged in
  <% end %>
</div>
<div class="image">
  <%= image_tag @catalogitem.photo, class: "img-responsive"%>
</div>
<div class="container-fluid">
  <div class="row stockitem-data">
    <div class="col-xs-4">
      <ul>
        <li>Retail price:</li>
        <li>Brand:</li>
        <li>Description:</li>
        <li>Release Date:</li>
        <li>Product Code:</li>
        <li>Colour:</li>
      </ul>
    </div>
    <div class="col-xs-8">
        <ul>
          <li>€ <%= @catalogitem.retail_price %></li>
          <li><%= @catalogitem.brand %></li>
          <li><%= @catalogitem.description %></li>
          <li><%= @catalogitem.release_date %></li>
          <li><%= @catalogitem.product_code %></li>
          <li><%= @catalogitem.colour %></li>
        </ul>
    </div>
  </div>
</div>
<%= button_to "Sell", new_stockitem_path(@catalogitem), method: "get", class: "btn-small" %>