config/routes.rb
Rails.application.routes.draw do
  # devise_for :users

  devise_for :users, controllers: {
  registrations: "registrations",
}

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :stockitems do
    resource :bids, only: [:new, :create, :index]
    # resource :orders, only: [:new, :create, :show]
  end
  resources :orders, except: [:destroy]
  resources :bids, only: :destroy
  resources :catalogitems, except: [:destroy]
  resources :orderstatuses, only: [:index]
  resources :users, only: [:show, :index]
  resources :transactions, only: [:show] do
    resources :payments, only: [:new, :create]
  end
end

app/views/pages/home.html.erb
<div id="myCarousel" class="carousel slide" data-ride="carousel">

  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item active">
      <%= image_tag "img36.jpg", alt: "Shoe number 1" %>
      <div class="carousel-caption">
        <p>Air Vapormax Off White 2018</p>
      </div>
    </div>

    <div class="item">
      <%= image_tag "Air-Jordan-1-Retro-High-Satin-Shattered-Backboard-W.png", height: "350", alt: "Air Jordan 1 Retro High Satin Shattered Backboard" %>
      <div class="carousel-caption">
        <p>Air Jordan 1 Retro High Satin Shattered Backboard</p>
      </div>
    </div>

    <div class="item">
      <%= image_tag "air-jordan-11-retro-win-like-96-Product.jpg", height: "350", alt: "air-jordan-11-retro-win-like-96-Product" %>
      <div class="carousel-caption">
        <p>air jordan 11 retro win like 96</p>
      </div>
    </div>
  </div>

  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<!-- <div class="development">
  developer info: <br />
  <%# if current_user %>
  current_user: <%#= current_user.email  %>
  admin: <%#= current_user.admin %>
  <%# else %>
  no user logged in
  <%# end %>
</div> -->
<div class="justify">
  <%= button_to "Market", stockitems_path, method: "get", class: "knop-1" %>
  <%= button_to "Catalogue Items", catalogitems_path, method: "get", class: "knop-1" %>
  <% if user_signed_in? && current_user.admin  %>
    <%= button_to "Orders", orders_path, method: "get", class: "knop-1"%>
    <%= button_to "Users", users_path, method: "get", class: "knop-1"%>
  <% end %>
</div>




<!-- <div class="container-fluid">
  <h1 class="text-center mb-3">Top sellers</h1>
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner row w-100 mx-auto">
      <div class="carousel-item col-md-4 active">
        <div class="card">
 -->          <!-- <img class="card-img-top img-fluid" src="../../assets/images/img36.jpeg" alt="Card image cap"> -->
          <%#= image_tag "img36.jpeg", class: "card-img-top img-fluid" %>
<!--           <div class="card-body">
            <h4 class="card-title">Card 1</h4>
            <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
            <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
          </div>
        </div>
      </div>
      <div class="carousel-item col-md-4">
        <div class="card">
          <img class="card-img-top img-fluid" src="http://placehold.it/800x600/418cf4/fff" alt="Card image cap">
          <div class="card-body">
            <h4 class="card-title">Card 2</h4>
            <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
            <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
          </div>
        </div>
      </div>
      <div class="carousel-item col-md-4">
        <div class="card">
          <img class="card-img-top img-fluid" src="http://placehold.it/800x600/3ed846/fff" alt="Card image cap">
          <div class="card-body">
            <h4 class="card-title">Card 3</h4>
            <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
            <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
          </div>
        </div>
      </div>
      <div class="carousel-item col-md-4">
        <div class="card">
          <img class="card-img-top img-fluid" src="http://placehold.it/800x600/42ebf4/fff" alt="Card image cap">
          <div class="card-body">
            <h4 class="card-title">Card 4</h4>
            <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
            <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
          </div>
        </div>
      </div>
      <div class="carousel-item col-md-4">
        <div class="card">
          <img class="card-img-top img-fluid" src="http://placehold.it/800x600/f49b41/fff" alt="Card image cap">
          <div class="card-body">
            <h4 class="card-title">Card 5</h4>
            <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
            <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
          </div>
        </div>
      </div>
      <div class="carousel-item col-md-4">
        <div class="card">
          <img class="card-img-top img-fluid" src="http://placehold.it/800x600/f4f141/fff" alt="Card image cap">
          <div class="card-body">
            <h4 class="card-title">Card 6</h4>
            <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
            <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
          </div>
        </div>
      </div>
      <div class="carousel-item col-md-4">
        <div class="card">
          <img class="card-img-top img-fluid" src="http://placehold.it/800x600/8e41f4/fff" alt="Card image cap">
          <div class="card-body">
            <h4 class="card-title">Card 7</h4>
            <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
            <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
          </div>
        </div>
      </div>
    </div>
    <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div> -->